import AppShell from "@/components/AppShell";
import { AlertTriangle, Bell, Clock } from "lucide-react";

const Alerts = () => {
  const alerts = [
    {
      id: 1,
      type: "Low stock",
      severity: "high",
      message: "Whole Wheat Pasta (PRD-003) is in critical stock.",
      action: "Restock within 24 hours to avoid stockout.",
      time: "5 minutes ago"
    },
    {
      id: 2,
      type: "Overstock",
      severity: "medium",
      message: "Organic Coffee Beans (PRD-001) are above optimal stock.",
      action: "Run a promotion to reduce excess inventory.",
      time: "30 minutes ago"
    },
    {
      id: 3,
      type: "Reorder suggestion",
      severity: "low",
      message: "Premium Olive Oil (PRD-002) is trending down.",
      action: "Create a purchase order for the next 2 weeks of demand.",
      time: "2 hours ago"
    }
  ];

  return (
    <AppShell>
      <div className="space-y-8 max-w-[900px] mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div>
          <h1 className="text-3xl font-display font-bold text-white tracking-tight">System Alerts</h1>
          <p className="text-sm text-muted-foreground mt-2 font-medium">
            See inventory risks and recommended actions generated by SmartStock heuristics.
          </p>
        </div>

        <div className="bg-card backdrop-blur-glass border border-warning/20 rounded-2xl p-5 flex items-center gap-4 shadow-[0_0_15px_rgba(245,158,11,0.1)] hover:border-warning/40 transition-all">
          <div className="p-3 rounded-xl bg-warning/20 border border-warning/30 shadow-[0_0_15px_rgba(245,158,11,0.4)]">
            <Bell className="h-5 w-5 text-warning animate-pulse" />
          </div>
          <div className="text-sm font-medium text-white/90 leading-relaxed">
            Alerts are prioritized by <span className="font-bold text-warning">risk level</span> so you can resolve the most critical dependencies first.
          </div>
        </div>

        <div className="space-y-4">
          {alerts.map((alert, i) => {
            const isHigh = alert.severity === "high";
            const isMed = alert.severity === "medium";
            
            const borderColors = isHigh ? "border-critical/30" : isMed ? "border-warning/30" : "border-info/30";
            const shadowColors = isHigh ? "shadow-[0_0_15px_rgba(239,68,68,0.2)]" : isMed ? "shadow-[0_0_15px_rgba(245,158,11,0.2)]" : "shadow-[0_0_15px_rgba(59,130,246,0.2)]";
            const iconBgClass = isHigh ? "bg-critical/20" : isMed ? "bg-warning/20" : "bg-info/20";
            const iconColorClass = isHigh ? "text-critical" : isMed ? "text-warning" : "text-info";
            const textBgClass = isHigh ? "bg-critical/10 text-critical border border-critical/20" : isMed ? "bg-warning/10 text-warning border border-warning/20" : "bg-info/10 text-info border border-info/20";
            
            return (
            <div
              key={alert.id}
              className={`group bg-card backdrop-blur-glass border ${borderColors} rounded-2xl p-6 flex items-start gap-5 ${shadowColors} hover:-translate-y-1 hover:border-white/20 transition-all duration-300 relative overflow-hidden`}
              style={{ animationDelay: `${i * 100}ms` }}
            >
              <div className={`absolute top-0 right-0 -m-8 w-24 h-24 rounded-full blur-2xl opacity-20 transition-colors pointer-events-none ${iconBgClass}`} />
              
              <div
                className={`flex-shrink-0 p-3.5 rounded-xl border border-white/10 ${iconBgClass} ${iconColorClass} relative z-10`}
              >
                <AlertTriangle className="h-5 w-5" />
              </div>
              
              <div className="flex-1 relative z-10">
                <div className="flex items-center justify-between gap-2 border-b border-white/5 pb-3 mb-3">
                  <div className="flex items-center gap-3">
                    <span className="text-base font-bold text-white drop-shadow-sm">{alert.type}</span>
                    <span
                      className={`text-[10px] px-2.5 py-0.5 rounded-full uppercase tracking-widest font-bold shadow-inner ${textBgClass}`}
                    >
                      {alert.severity} Risk
                    </span>
                  </div>
                  <div className="flex items-center gap-1.5 text-xs font-bold text-muted-foreground group-hover:text-white/70 transition-colors">
                    <Clock className="h-3.5 w-3.5" />
                    <span>{alert.time}</span>
                  </div>
                </div>
                
                <p className="text-sm font-medium text-muted-foreground">
                  {alert.message}
                </p>
                
                <p className="inline-block mt-4 px-3.5 py-1.5 rounded-lg text-xs font-bold bg-success/10 text-success border border-success/30 shadow-[0_0_10px_rgba(16,185,129,0.2)] group-hover:bg-success/20 transition-colors">
                  Action: {alert.action}
                </p>
              </div>
            </div>
            );
          })}
        </div>
      </div>
    </AppShell>
  );
};

export default Alerts;